/nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/Main.o /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/Main.or /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/Main.od /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/Main.op:  \
 /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/Main.cc \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/System.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/IntTypes.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/ParseUtils.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/Options.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Vec.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/IntTypes.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/XAlloc.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/ParseUtils.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/core/Dimacs.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/ParseUtils.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/core/SolverTypes.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/IntTypes.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Alg.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Vec.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Vec.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Map.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Alloc.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/core/MinimalCore.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/SimpSolver.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Queue.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/core/Solver.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Heap.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/Options.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/core/ResolutionGraph.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Set.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Map.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/SimpSolver.h
/nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/SimpSolver.o /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/SimpSolver.or /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/SimpSolver.od /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/SimpSolver.op:  \
 /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/SimpSolver.cc \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Sort.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Vec.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/IntTypes.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/XAlloc.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/simp/SimpSolver.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Queue.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/core/Solver.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Vec.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Heap.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Alg.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/Options.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/IntTypes.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Vec.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/ParseUtils.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/core/SolverTypes.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/IntTypes.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Map.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Alloc.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/core/ResolutionGraph.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Set.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/mtl/Map.h \
  /nfs/iil/proj/dt/prover01/work/vryvchin/minisat/minisat2.2/icmuc_resol_pre/utils/System.h
